import type { Metadata } from "next";
import localFont from "next/font/local"
import "./globals.css";

const SFProDisplay = localFont({
  src: "./fonts/sf-pro-display-regular.woff2",
  variable: "--font-sf-pro-display",
  weight: "400 900"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SFProDisplay.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
